### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by NathanDuma** [JoshuaDuma/FakeApi#1]
Help

**Comment by JoshuaDuma** [comment]
Hello!

You can run this in docker using this command: `docker run -p 2084:2084 socoolbro/fakeapi:latest`. You can then view the Swagger documentation here: http://localhost:2084/api-docs. You can make requests using GET requests to endpoints, as seen in Swagger.

Please let me know if you have any other questions.

**Comment by NathanDuma** [comment]
I got an error . How do i fix?

**Comment by JoshuaDuma** [comment]
Please attach a screenshot of the error.

**Comment by NathanDuma** [comment]
![image](https://user-images.githubusercontent.com/11504916/169473478-5cc779ad-ea32-45ee-b6a7-58826468f9ce.png)

**Comment by NathanDuma** [comment]
Help

**Comment by NathanDuma** [comment]
Hi any update on this?

**Comment by NathanDuma** [comment]
Please reopen, this is not fixed.
